version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
      target: runner
    container_name: conecta_caparao_app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.conecta-caparao.rule=Host(`incaper.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.conecta-caparao.entrypoints=websecure"
      - "traefik.http.routers.conecta-caparao.tls.certresolver=letsencrypt"
      - "traefik.http.services.conecta-caparao.loadbalancer.server.port=3000"
      - "traefik.docker.network=web"
    networks:
      - web
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  web:
    external: true
