name: Production CD

on:
  push:
    branches: [ main ]

jobs:
  ci:
    uses: ./.github/workflows/base-ci.yml
    with:
      node-version: '18'
      continue-on-security-error: false  # Production pipeline is strict

  deploy:
    name: Deploy to Production
    needs: ci
    if: success()
    uses: ./.github/workflows/deploy.yml
    with:
      environment: 'production'
      docker-compose-file: 'docker-compose.prod.yaml'
      health-check-url: 'http://localhost:3000/api/health'
    secrets:
      VPC_SSH_PRIVATE_KEY: ${{ secrets.VPC_SSH_PRIVATE_KEY }}
      VPC_HOST: ${{ secrets.VPC_HOST }}
      VPC_USER: ${{ secrets.VPC_USER }}
      VPC_PROJECT_PATH: ${{ secrets.VPC_PROJECT_PATH }}